# Generated by Django 2.0.6 on 2019-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cityOrigin', models.CharField(max_length=200)),
                ('richOrPowers', models.CharField(choices=[('rich', 'I am Rich'), ('super', 'I have superpowers')], max_length=200)),
                ('powers', models.CharField(choices=[('Flight', 'Flight'), ('Speed', 'Speed'), ('Invisibility', 'Invisibility'), ('Telekenetic', 'Telekenetic'), ('Healing', 'Healing'), ('Other', 'Other')], max_length=200)),
                ('integrity', models.CharField(choices=[('Good', 'Good'), ('kinda Good', 'Kinda Good'), ('Neutral', 'Neutral'), ('a little evil', 'A Little Evil'), ('Evil', 'Evil')], max_length=200)),
            ],
        ),
    ]
