# Generated by Django 2.0.6 on 2019-03-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registationmodel',
            name='useOfPowers',
            field=models.TextField(default='', max_length=600000),
            preserve_default=False,
        ),
    ]
